Module declare

   IMPLICIT NONE

   INTEGER JOBID,PARAL,GMODE
   INTEGER SEED,LAVE,JREPEAT,NREPEAT
   INTEGER NUNIT,NSTRDAVE,NSTRAND,NSUBUNI,NLOOP
   INTEGER NCYL,NCAP,NCLOSEDHOOP,NLEFT,NDOWN,NUP,N0,RES0
   INTEGER NATOM,NATOMCAP,NPG,IPG,NESTI
   INTEGER NPHI0,NC1,NC2,N1SYM,N2SYM,NPICKSYM,JSYM
   INTEGER NBOND,NBONDGLY,NBONDPEP,NLINE
   INTEGER J1,J2,J3,J4,J5,J6,J7,J8,J9
   INTEGER I,J,I0,I1,I2,J0,IBOND,N,N1,N2,N3,K,NPHI,LENGTH
   INTEGER II,JJ,ISTART,JSTART,NBONDSTART,NATOMSTART,DI,DJ
   INTEGER INTERVAL,JR,NB,JL,NB1,JPICK,JB1,JB2
   INTEGER ISEG
   INTEGER NCOUNT,NPOST,STOPA,NPICK,CHECK
   INTEGER ILOOP,NRUN,NEXT,NEXT1,NEXT2
   INTEGER NPGTOTAL,PGCAP1,PGCAP2
   INTEGER PGLENMAX,LOOPLENMAX
   INTEGER NINS,NTHREAD,NTHREADSET,OMP_GET_NUM_THREADS
   INTEGER NREMOD,NSTEP,STOPP,NSTART,IPRES,NR,NC
   INTEGER NPRINT,JPRINT1,JPRINT2,JPRINT,OMP_GET_THREAD_NUM,NPEP,NTHE
   INTEGER NRATIO,JFORCE
   INTEGER YEARS,MONS,TIMERUN,DAYS,HOURS,MINS,SECS,LASTTIME,TIMESTART,TIME0,NM

   INTEGER NATOMMAX,NSYN,NSYNMAX,NPGMAX,NGLYMAX,NPEPMAX,NLOOPMAX
   INTEGER SYNRATIO,NB2,JRESET,BACKCRLK
   INTEGER NBONDDEL,NBONDGLYSTART,NSIG
   INTEGER NL,NLOOPDEL
   INTEGER JLYT,JCHECK1,JCHECK2
   INTEGER JSTEP,SLOWLOAD
   INTEGER NTIP,NPREV,JLINK,NNEW,JRFORCE,NRAND
   INTEGER NS,NS1,NPEPTOTAL,NPGSTART,NGLYNEW
   INTEGER NATOMDEL,OLDNATOMDEL,NDEL,NA
   INTEGER JFILE,JS,NTRAP,JCHANGE
   INTEGER JUNIT,NSYNREP,NTRANS,NHOLD,NRELAX,JEXIT,JCRLK,JBEND,JLONG

   INTEGER NH,NEWNATOMCAP,LEFTCELL,RITECELL
   INTEGER JA1,JA2,JGET,JA,JB,LENA,LENB,JSKIP,LOLEN,NGET
   INTEGER NEWPGCAP1,NEWPGCAP2
   INTEGER LENHOOP,LENHOOP0,NSIZE
   INTEGER NA1,NA2,NDIV
   INTEGER ND,NLINK,JD,NANEW,NPGNEW,NBGLYNEW,NBPEPNEW,NLPNEW,JR0,NR0,JCYCLE
   INTEGER JCOUNT,LIST(3),DNORTEMP(100),ATORTEMP(100)
   INTEGER JJ1,JJ2,NL1,NL2,JAM,JA1M,JA2M,JBM,JB1M,JB2M,JGETM

   INTEGER, DIMENSION(:),ALLOCATABLE:: ATYP,APOST
   INTEGER, DIMENSION(:),ALLOCATABLE::XPOST,MATURE,JMARK,JMARKMIRROR
   INTEGER, DIMENSION(:,:),ALLOCATABLE:: PART
   INTEGER, DIMENSION(:),ALLOCATABLE::NPART,MARK,MARK1,MARK2,MARKCH,ITSPART

   INTEGER,DIMENSION(:),ALLOCATABLE:: EDOSIG,TP2SIG,EDCAP,JTRAP,JDEACT,JRANDS,JREINI,JPAIR
   INTEGER,DIMENSION(:,:),ALLOCATABLE::PGID,EDHOLD,SIGBOND,GTATRANS,EDPEP
   INTEGER,DIMENSION(:,:),ALLOCATABLE::NEWPGID,TRANSGLY,GLYTIP,GLYSEC
   INTEGER,DIMENSION(:),ALLOCATABLE::PGLEN,PGTYP,PGDIR,DNOR,ATOR,PEPDIR
   INTEGER,DIMENSION(:),ALLOCATABLE::NEWPGLEN,NEWPGTYP,NEWPGDIR,ATORNEW,DNORNEW,PEPDIRNEW
   INTEGER,DIMENSION(:,:),ALLOCATABLE::BOND,BONDGLY,BONDPEP
   INTEGER,DIMENSION(:,:),ALLOCATABLE::NEWBONDGLY,NEWBONDPEP,SIGCROSS,ADDSIG
   INTEGER,DIMENSION(:),ALLOCATABLE::BONTYP
   INTEGER,DIMENSION(:),ALLOCATABLE::NEWBONTYP,SYNMARK,JR_ENDO_ON,JR_ENDO_OFF,SIGCLEAVE,EDLOCKIN
   INTEGER,DIMENSION(:,:),ALLOCATABLE::LOOP,NEWLOOP
   INTEGER,DIMENSION(:,:),ALLOCATABLE::CRLKAGE,NETWORK,SYNTHESIS,GTLOAD,SYNPG,OLDSYNPG
   INTEGER,DIMENSION(:),ALLOCATABLE::LOOPLEN,NEWLOOPLEN,LOOPTYP,NEWLOOPTYP
   INTEGER,DIMENSION(:),ALLOCATABLE:: SYNDIR,SYNLOOP
   INTEGER,DIMENSION(:),ALLOCATABLE:: NEINUM,GLYNUM,GTAWAIT
   INTEGER,DIMENSION(:,:,:),ALLOCATABLE::NEIBOND,NEIGLY,TPPEP

   INTEGER,DIMENSION(:),ALLOCATABLE::MAP,PARTNER

   DOUBLE PRECISION RAD
   DOUBLE PRECISION XCEN0,YCEN0,ZCEN0
   DOUBLE PRECISION PHI,DPHI,PHI0,LCYL
   DOUBLE PRECISION W1,W2,D1,D2,RAT0,RAT1,RAT2
   DOUBLE PRECISION CHARG,MASS,DIST1,DIST2
   DOUBLE PRECISION L_G,K_G,L_P,L_PEP,K_P,THETA_0,KTHETA,PRES,VOLM,VOLMNEW,TEM
   DOUBLE PRECISION DX,DY,DZ,DX0,DY0,DZ0,YNOR,ZNOR,W0,W
   DOUBLE PRECISION X1,Y1,Z1,X2,Y2,Z2,NX,NY,NZ
   DOUBLE PRECISION ENG,ENGPRES,ENGBOND,ENGGLY,ENGPEP,ENGTHETA,ENEW
   DOUBLE PRECISION ENGNEW,ENGPRESNEW,ENGBONDNEW,ENGGLYNEW,ENGPEPNEW,ENGTHETANEW
   DOUBLE PRECISION GAM,R,PROB,FAVE,FMAX

   DOUBLE PRECISION PI != 3.141592653589793239D0
   DOUBLE PRECISION P_ENDO_ON,P_ENDO_OFF
   DOUBLE PRECISION PSTART,PSTOP,PTERM,P_GLYIN,P_PEPIN,P_PEPOUT,P_EDHOLD
   DOUBLE PRECISION PMATURE,PLYT,GROWTH,P_GLYOUT,PBEND,P_TRANSFAST,P_TRANSSLOW
   DOUBLE PRECISION XCAP1,XCAP2,FAMAX,DREACT,DREACT2
   DOUBLE PRECISION FPMAX1,FPMAX2,FPMAX3,FPMAX4,FPMAX5,FPMAX6
   DOUBLE PRECISION FPBPMAX,INVMPBP,AREA,ORAD
   DOUBLE PRECISION LSTART,LREP,LSWITCH,KSWITCH,MSWITCH
   DOUBLE PRECISION KGTASE,KTPASE,LTPASE,KPAIR,LPAIR,KGTTP,LGTTP
   DOUBLE PRECISION KEDASE,LEDASE,KGTED,LGTED,KWALL,KLEAD,DELTA,INVDELTA,BETA,KSUR,KSIDE,LSIDE

   DOUBLE PRECISION RATIO,ARG1,ARG2,XPG,YPG,ZPG,XLOOP,YLOOP,ZLOOP,XB,YB,ZB,XSHIFT
   DOUBLE PRECISION VX,VY,VZ,RADIUS,RADIUS0
   DOUBLE PRECISION RXX,RXY,RXZ,RYX,RYY,RYZ,RZX,RZY,RZZ,ARG,DIST,SINP,COSP
   DOUBLE PRECISION DXNEW,DYNEW,DZNEW,XPRJ,YPRJ,ZPRJ,X0,Y0,Z0,X00,Y00,Z00,DELTAX

   DOUBLE PRECISION, DIMENSION(:),ALLOCATABLE:: ANGLE
   DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE:: X,Y,Z,XEDASEOLD,YEDASEOLD,ZEDASEOLD
   DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE:: XNEW,YNEW,ZNEW,XLEAD,YLEAD,ZLEAD,XEDASE,YEDASE,ZEDASE
   DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE::F,FX,FY,FZ,FAMAG,FXGLY,FYGLY,FZGLY,FXSUR,FYSUR,FZSUR
   DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE::FXPEP,FYPEP,FZPEP,FXTHETA,FYTHETA,FZTHETA
   DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE::FXPRES,FYPRES,FZPRES,FXSYN,FYSYN,FZSYN,FXCAPGT,FXCAPEDASE
   DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE::XGTASE,YGTASE,ZGTASE,FXGTASE,FYGTASE,FZGTASE,LGTASE
   DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE::FXTPASE,FYTPASE,FZTPASE,XTPASE,YTPASE,ZTPASE
   DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE::FXEDASE,FYEDASE,FZEDASE,FMAGPBP
   DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE::R1,R2,SYNRAD,ATOMRAD,ATOMRADNEW,GTRAD
   DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE::RXGTASE,RYGTASE,RZGTASE,RXTPASE,RYTPASE,RZTPASE
   DOUBLE PRECISION,DIMENSION(:,:),ALLOCATABLE::RXEDASE,RYEDASE,RZEDASE,RANDS
   DOUBLE PRECISION,DIMENSION(:),ALLOCATABLE:: XCEN,YCEN,ZCEN,UX,UY,UZ,LRAD,PCOUPLE

   CHARACTER (LEN=64) FILENAME
   CHARACTER ZERO*1,CHARID1*1,CHARID2*2,CHARID3*3,CHARID4*4

   character*4 coor
   character*80 string1,string2
   integer ifirst,nframe,nfreq,ntotal,zeros5(5),peroff,zeros7(7),two,twentyfour
   integer*8 jdelta
   real, dimension(:), allocatable  :: xw,yw,zw

   character (len=512) command,CHARA,ANSWER

   REAL VX0,VY0,VZ0

End module
