   PROGRAM LENGTHMEASURE

   IMPLICIT NONE

   INTEGER NSTART,N,NRES,RESLENMAX,I,LENGTH,NCOUNT
   INTEGER,DIMENSION(:),ALLOCATABLE::RESLEN,RESTYP
   INTEGER,DIMENSION(:,:),ALLOCATABLE::RESID

   CHARACTER ZERO*1,CHARID1*1,CHARID2*2,CHARID3*3,CHARID4*4
   CHARACTER CHARA*512
   CHARACTER (LEN=64) FILEDCD,FILECOOR,FILECONFIG

   OPEN(1,FILE='restart.inp')
   READ(1,*)NSTART,N
   CLOSE(1)

   WRITE(ZERO,'(I1)')0

   IF(NSTART<10)THEN
      WRITE(CHARID1,'(I1)')NSTART
      FILECOOR='coor'//ZERO//ZERO//ZERO//CHARID1//'.inp'
      FILECONFIG='config'//ZERO//ZERO//ZERO//CHARID1//'.inp'
   ELSE IF(NSTART<100)THEN
      WRITE(CHARID2,'(I2)')NSTART
      FILECOOR='coor'//ZERO//ZERO//CHARID2//'.inp'
      FILECONFIG='config'//ZERO//ZERO//CHARID2//'.inp'
   ELSE IF(NSTART<1000)THEN
      WRITE(CHARID3,'(I3)')NSTART
      FILECOOR='coor'//ZERO//CHARID3//'.inp'
      FILECONFIG='config'//ZERO//CHARID3//'.inp'
   ELSE IF(NSTART<10000)THEN
      WRITE(CHARID4,'(I4)')NSTART
      FILECOOR='coor'//CHARID4//'.inp'
      FILECONFIG='config'//CHARID4//'.inp'
   ELSE
      PRINT*,'NSTART IS TOO BIG! STOP NOW.'
      STOP
   END IF

   OPEN(1,FILE=FILECONFIG)

2  READ(1,*)CHARA
   IF(CHARA(1:4)/='RESI')THEN
      GOTO 2
   END IF

   READ(1,*)N,NRES,RESLENMAX

   ALLOCATE(RESID(RESLENMAX,NRES),RESLEN(NRES),RESTYP(NRES))

   DO I=1,NRES
      READ(1,*)RESLEN(I),RESTYP(I),N,RESID(1:RESLEN(I),I)
   END DO

   CLOSE(1)

   LENGTH=0
   NCOUNT=0

   DO I=1,NRES

      IF(RESTYP(I)==3)THEN
         LENGTH=LENGTH+RESLEN(I)
         NCOUNT=NCOUNT+1
      END IF

   END DO

   PRINT*,'AVERAGE LENGTH OF NEW PG',1.0*LENGTH/NCOUNT

   END
